### ISSUE TITLE
SAT6-Workshop/documentation/_includes/Activation-Keys.adoc

### ISSUE THREAD

**Issue by bluey64** [xtophd/SAT6-Workshop#2]
* the activation key creation for the "Desktop-prod"  has a typing error.

hammer activation-key create \
--name "desktop-**prob**" \
--description "Desktops for development and early testing" \
--lifecycle-environment "Desktop-PROD" \
--content-view "Desktop-R7"  \
--organization "ExampleCom"

This should be "Desktop-prod" \

hammer activation-key create \
--name "desktop-**prod**" \
--description "Desktops for development and early testing" \
--lifecycle-environment "Desktop-PROD" \
--content-view "Desktop-R7"  \
--organization "ExampleCom"

**Comment by xtophd** [comment]
fixed...thank you
